export const CORE_CAPABILITIES = [
  'machine.snapshot',
  'machine.health',
  'nexowire.update.status',
  'nexowire.update.check',
  'nexowire.update.apply',
  'network.dns.resolve',
  'network.tcp.probe',
  'network.http.probe',
  'shell.exec',
  'process.start',
  'process.read',
  'process.write',
  'process.stop',
  'process.list',
  'process.prune',
  'wsl.exec',
  'files.read',
  'files.read_many',
  'files.write',
  'files.stat',
  'files.hash',
  'files.mkdir',
  'files.copy',
  'files.move',
  'files.delete',
  'files.patch',
  'files.list',
  'search.text',
  'workspace.snapshot',
  'workspace.detect',
  'workspace.checks',
  'task.graph.run',
  'task.graph.list',
  'task.graph.get',
  'task.graph.prune',
  'task.artifact.list',
  'task.artifact.verify',
  'runbook.run',
  'runbook.list',
  'runbook.get',
  'runbook.prune',
  'windows.uac.status',
  'windows.processes',
  'windows.services',
  'windows.network.snapshot',
  'windows.service.control',
  'windows.registry.read',
  'windows.tasks',
  'windows.eventlog.query',
  'windows.firewall.rules',
  'windows.registry.set',
  'windows.registry.delete',
  'windows.task.control',
  'windows.firewall.control',
  'windows.environment.list',
  'windows.environment.read',
  'windows.environment.set',
  'windows.environment.delete',
  'windows.installer.apply',
  'windows.installer.status',
  'windows.window.list',
  'windows.window.focus',
  'windows.screenshot',
  'windows.clipboard.read',
  'windows.clipboard.write',
  'windows.clipboard.clear',
  'windows.keyboard.type',
  'windows.keyboard.hotkey',
  'windows.accessibility.tree',
  'windows.accessibility.find',
  'windows.accessibility.invoke',
  'windows.accessibility.set_value',
  'windows.pointer.position',
  'windows.pointer.move',
  'windows.pointer.click',
  'windows.pointer.scroll',
  'windows.virtual_pointer.status',
  'windows.virtual_pointer.start',
  'windows.virtual_pointer.stop',
  'windows.virtual_pointer.move',
  'windows.virtual_pointer.style',
  'windows.virtual_pointer.visibility',
  'windows.private_screen.capture',
  'windows.private_viewer.status',
  'windows.private_viewer.start',
  'windows.private_viewer.stop',
  'windows.private_desktop.status',
  'windows.private_desktop.start',
  'windows.private_desktop.stop',
  'windows.private_desktop.launch',
  'windows.private_desktop.windows',
  'windows.private_desktop.show',
  'windows.private_pointer.move',
  'windows.private_pointer.click',
  'windows.private_keyboard.type',
  'windows.private_keyboard.hotkey',
  'windows.console_control.status',
  'windows.console_control.request',
  'windows.console_control.revoke',
  'browser.session.start',
  'browser.session.list',
  'browser.session.stop',
  'browser.tabs',
  'browser.navigate',
  'browser.snapshot',
  'browser.click',
  'browser.set_value',
  'browser.screenshot',
  'browser.visual.verify',
  'verify.assertions',
] as const;

export type CoreCapability = (typeof CORE_CAPABILITIES)[number];
export type Capability = CoreCapability | (string & {});

export function hasCapability(
  capabilities: readonly string[],
  capability: string,
): boolean {
  return capabilities.includes(capability);
}

export function capabilitiesForPlatform(platform: NodeJS.Platform): string[] {
  return CORE_CAPABILITIES.filter((capability) => {
    if (capability.startsWith('windows.')) return platform === 'win32';
    if (capability === 'wsl.exec') return platform === 'win32';
    return true;
  });
}

export const READ_ONLY_CAPABILITIES = new Set<string>([
  'machine.snapshot',
  'machine.health',
  'nexowire.update.status',
  'nexowire.update.check',
  'network.dns.resolve',
  'network.tcp.probe',
  'network.http.probe',
  'process.read',
  'process.list',
  'files.read',
  'files.read_many',
  'files.stat',
  'files.hash',
  'files.list',
  'search.text',
  'workspace.snapshot',
  'workspace.detect',
  'task.graph.list',
  'task.graph.get',
  'task.artifact.list',
  'task.artifact.verify',
  'runbook.list',
  'runbook.get',
  'windows.uac.status',
  'windows.processes',
  'windows.services',
  'windows.network.snapshot',
  'windows.registry.read',
  'windows.tasks',
  'windows.eventlog.query',
  'windows.firewall.rules',
  'windows.environment.list',
  'windows.environment.read',
  'windows.installer.status',
  'windows.window.list',
  'windows.screenshot',
  'windows.clipboard.read',
  'windows.accessibility.tree',
  'windows.accessibility.find',
  'windows.pointer.position',
  'windows.virtual_pointer.status',
  'windows.private_screen.capture',
  'windows.private_viewer.status',
  'windows.private_desktop.status',
  'windows.private_desktop.windows',
  'windows.console_control.status',
  'browser.session.list',
  'browser.tabs',
  'browser.snapshot',
  'browser.screenshot',
  'browser.visual.verify',
  'verify.assertions',
]);

export function isReadOnlyCapability(capability: string): boolean {
  return READ_ONLY_CAPABILITIES.has(capability);
}
