export const MCP_SURFACE_VERSION = 1 as const;

/**
 * Tool names that form the Nexowire MCP v1 compatibility floor.
 *
 * Additive tools do not require a surface version bump. Removing, renaming,
 * or changing one of these tools incompatibly requires a new surface version
 * and a documented migration path.
 */
export const MCP_V1_STABLE_TOOLS = [
  "audit_query",
  "audit_recent",
  "browser_click",
  "browser_navigate",
  "browser_screenshot",
  "browser_session_list",
  "browser_session_start",
  "browser_session_stop",
  "browser_set_value",
  "browser_snapshot",
  "browser_tabs",
  "browser_visual_verify",
  "device_alias_delete",
  "device_alias_list",
  "device_alias_set",
  "device_group_delete",
  "device_group_list",
  "device_group_set",
  "device_route",
  "device_route_policy_delete",
  "device_route_policy_list",
  "device_route_policy_resolve",
  "device_route_policy_set",
  "devices_list",
  "events_read",
  "file_copy",
  "file_delete",
  "file_hash",
  "file_list",
  "file_mkdir",
  "file_move",
  "file_patch",
  "file_read",
  "file_read_many",
  "file_stat",
  "file_write",
  "machine_health",
  "machine_snapshot",
  "network_dns_resolve",
  "network_http_probe",
  "network_tcp_probe",
  "nexowire_surface_info",
  "operations_idempotency_list",
  "policy_device_bind",
  "policy_device_check",
  "policy_device_unbind",
  "policy_profile_delete",
  "policy_profile_list",
  "policy_profile_set",
  "process_list",
  "process_prune",
  "process_read",
  "process_start",
  "process_stop",
  "process_write",
  "runbook_get",
  "runbook_list",
  "runbook_prune",
  "runbook_run",
  "search_text",
  "shell_exec",
  "skill_read",
  "skills_list",
  "task_artifact_list",
  "task_artifact_verify",
  "task_graph_get",
  "task_graph_list",
  "task_graph_prune",
  "task_run_graph",
  "verify_assertions",
  "windows_accessibility_find",
  "windows_accessibility_invoke",
  "windows_accessibility_set_value",
  "windows_accessibility_tree",
  "windows_clipboard_clear",
  "windows_clipboard_read",
  "windows_clipboard_write",
  "windows_environment_delete",
  "windows_environment_list",
  "windows_environment_read",
  "windows_environment_set",
  "windows_eventlog_query",
  "windows_firewall_control",
  "windows_firewall_rules",
  "windows_keyboard_hotkey",
  "windows_keyboard_type",
  "windows_network_snapshot",
  "windows_pointer_click",
  "windows_pointer_move",
  "windows_pointer_position",
  "windows_pointer_scroll",
  "windows_processes",
  "windows_registry_delete",
  "windows_registry_read",
  "windows_registry_set",
  "windows_screenshot",
  "windows_service_control",
  "windows_services",
  "windows_task_control",
  "windows_tasks",
  "windows_window_focus",
  "windows_window_list",
  "workspace_checkpoint_get",
  "workspace_checkpoint_list",
  "workspace_checkpoint_save",
  "workspace_detect",
  "workspace_run_checks",
  "workspace_snapshot",
  "wsl_exec"
] as const;

export type McpV1StableTool =
  (typeof MCP_V1_STABLE_TOOLS)[number];

export function isMcpV1StableTool(
  toolName: string,
): toolName is McpV1StableTool {
  return (
    MCP_V1_STABLE_TOOLS as readonly string[]
  ).includes(toolName);
}
